/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multichannel.model;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ChannelScopeRel service. Represents a row in the &quot;ChannelScopeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.multichannel.model.impl.ChannelScopeRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.multichannel.model.impl.ChannelScopeRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChannelScopeRel
 * @generated
 */
@ProviderType
public interface ChannelScopeRelModel
	extends BaseModel<ChannelScopeRel>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a channel scope rel model instance should use the {@link ChannelScopeRel} interface instead.
	 */

	/**
	 * Returns the primary key of this channel scope rel.
	 *
	 * @return the primary key of this channel scope rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this channel scope rel.
	 *
	 * @param primaryKey the primary key of this channel scope rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the entry ID of this channel scope rel.
	 *
	 * @return the entry ID of this channel scope rel
	 */
	public long getEntryId();

	/**
	 * Sets the entry ID of this channel scope rel.
	 *
	 * @param entryId the entry ID of this channel scope rel
	 */
	public void setEntryId(long entryId);

	/**
	 * Returns the company ID of this channel scope rel.
	 *
	 * @return the company ID of this channel scope rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this channel scope rel.
	 *
	 * @param companyId the company ID of this channel scope rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the channel ID of this channel scope rel.
	 *
	 * @return the channel ID of this channel scope rel
	 */
	public long getChannelId();

	/**
	 * Sets the channel ID of this channel scope rel.
	 *
	 * @param channelId the channel ID of this channel scope rel
	 */
	public void setChannelId(long channelId);

	/**
	 * Returns the scope ID of this channel scope rel.
	 *
	 * @return the scope ID of this channel scope rel
	 */
	public long getScopeId();

	/**
	 * Sets the scope ID of this channel scope rel.
	 *
	 * @param scopeId the scope ID of this channel scope rel
	 */
	public void setScopeId(long scopeId);

}