/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.multichannel.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.multichannel.model.ChannelScopeRel;
import com.liferay.multichannel.model.ChannelScopeRelModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the ChannelScopeRel service. Represents a row in the &quot;ChannelScopeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>ChannelScopeRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ChannelScopeRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ChannelScopeRelImpl
 * @generated
 */
@ProviderType
public class ChannelScopeRelModelImpl
	extends BaseModelImpl<ChannelScopeRel> implements ChannelScopeRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a channel scope rel model instance should use the <code>ChannelScopeRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "ChannelScopeRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"entryId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"channelId", Types.BIGINT}, {"scopeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("entryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("channelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("scopeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ChannelScopeRel (entryId LONG not null primary key,companyId LONG,channelId LONG,scopeId LONG)";

	public static final String TABLE_SQL_DROP = "drop table ChannelScopeRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY channelScopeRel.entryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ChannelScopeRel.entryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CHANNELID_COLUMN_BITMASK = 1L;

	public static final long ENTRYID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ChannelScopeRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _entryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _entryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ChannelScopeRel.class;
	}

	@Override
	public String getModelClassName() {
		return ChannelScopeRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ChannelScopeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ChannelScopeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChannelScopeRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ChannelScopeRel)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ChannelScopeRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ChannelScopeRel, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ChannelScopeRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ChannelScopeRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ChannelScopeRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ChannelScopeRel>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ChannelScopeRel.class.getClassLoader(), ChannelScopeRel.class,
			ModelWrapper.class);

		try {
			Constructor<ChannelScopeRel> constructor =
				(Constructor<ChannelScopeRel>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<ChannelScopeRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ChannelScopeRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ChannelScopeRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<ChannelScopeRel, Object>>();
		Map<String, BiConsumer<ChannelScopeRel, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<ChannelScopeRel, ?>>();

		attributeGetterFunctions.put("entryId", ChannelScopeRel::getEntryId);
		attributeSetterBiConsumers.put(
			"entryId",
			(BiConsumer<ChannelScopeRel, Long>)ChannelScopeRel::setEntryId);
		attributeGetterFunctions.put(
			"companyId", ChannelScopeRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<ChannelScopeRel, Long>)ChannelScopeRel::setCompanyId);
		attributeGetterFunctions.put(
			"channelId", ChannelScopeRel::getChannelId);
		attributeSetterBiConsumers.put(
			"channelId",
			(BiConsumer<ChannelScopeRel, Long>)ChannelScopeRel::setChannelId);
		attributeGetterFunctions.put("scopeId", ChannelScopeRel::getScopeId);
		attributeSetterBiConsumers.put(
			"scopeId",
			(BiConsumer<ChannelScopeRel, Long>)ChannelScopeRel::setScopeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getEntryId() {
		return _entryId;
	}

	@Override
	public void setEntryId(long entryId) {
		_entryId = entryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getChannelId() {
		return _channelId;
	}

	@Override
	public void setChannelId(long channelId) {
		_columnBitmask |= CHANNELID_COLUMN_BITMASK;

		if (!_setOriginalChannelId) {
			_setOriginalChannelId = true;

			_originalChannelId = _channelId;
		}

		_channelId = channelId;
	}

	public long getOriginalChannelId() {
		return _originalChannelId;
	}

	@Override
	public long getScopeId() {
		return _scopeId;
	}

	@Override
	public void setScopeId(long scopeId) {
		_scopeId = scopeId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ChannelScopeRel.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ChannelScopeRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ChannelScopeRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ChannelScopeRelImpl channelScopeRelImpl = new ChannelScopeRelImpl();

		channelScopeRelImpl.setEntryId(getEntryId());
		channelScopeRelImpl.setCompanyId(getCompanyId());
		channelScopeRelImpl.setChannelId(getChannelId());
		channelScopeRelImpl.setScopeId(getScopeId());

		channelScopeRelImpl.resetOriginalValues();

		return channelScopeRelImpl;
	}

	@Override
	public int compareTo(ChannelScopeRel channelScopeRel) {
		long primaryKey = channelScopeRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof ChannelScopeRel)) {
			return false;
		}

		ChannelScopeRel channelScopeRel = (ChannelScopeRel)obj;

		long primaryKey = channelScopeRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ChannelScopeRelModelImpl channelScopeRelModelImpl = this;

		channelScopeRelModelImpl._originalChannelId =
			channelScopeRelModelImpl._channelId;

		channelScopeRelModelImpl._setOriginalChannelId = false;

		channelScopeRelModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ChannelScopeRel> toCacheModel() {
		ChannelScopeRelCacheModel channelScopeRelCacheModel =
			new ChannelScopeRelCacheModel();

		channelScopeRelCacheModel.entryId = getEntryId();

		channelScopeRelCacheModel.companyId = getCompanyId();

		channelScopeRelCacheModel.channelId = getChannelId();

		channelScopeRelCacheModel.scopeId = getScopeId();

		return channelScopeRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ChannelScopeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ChannelScopeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChannelScopeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((ChannelScopeRel)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ChannelScopeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ChannelScopeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ChannelScopeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ChannelScopeRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ChannelScopeRel>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _entryId;
	private long _companyId;
	private long _channelId;
	private long _originalChannelId;
	private boolean _setOriginalChannelId;
	private long _scopeId;
	private long _columnBitmask;
	private ChannelScopeRel _escapedModel;

}