dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "3.0.0"
	compileOnly group: "org.osgi", name: "osgi.cmpn", version: "6.0.0"
	compileOnly project(":apps:auto-tagging:auto-tagging-api")
	
	compileInclude group: "org.apache.httpcomponents", name: "httpasyncclient", version: "4.1.3"
	compileInclude group: "org.apache.httpcomponents", name: "httpclient", version: "4.5.3"
	compileInclude group: "org.apache.httpcomponents", name: "httpcore", version: "4.4.6"
	compileInclude group: "org.apache.httpcomponents", name: "httpcore-nio", version: "4.4.6"

	compileInclude group: "org.elasticsearch.client", name: "elasticsearch-rest-high-level-client", version: "6.1.4"
	compileInclude group: 'org.elasticsearch', name: 'elasticsearch', version: '6.1.4'
	compileInclude group: "org.elasticsearch.client", name: "elasticsearch-rest-client", version: "6.1.4"

	compileOnly group: "biz.aQute.bnd", name: "biz.aQute.bndlib", version: "3.5.0"
	compileOnly group: "com.liferay", name: "com.liferay.portal.configuration.metatype", version: "2.0.0"
	compileOnly project(":apps:auto-tagging:auto-tagging-api")
}