/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.editor.configuration.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the EditorConfigurationEntry service. Represents a row in the &quot;EditorConfigurationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EditorConfigurationEntry
 * @see com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryImpl
 * @see com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryModelImpl
 * @generated
 */
@ProviderType
public interface EditorConfigurationEntryModel extends BaseModel<EditorConfigurationEntry>,
	ShardedModel, StagedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a editor configuration entry model instance should use the {@link EditorConfigurationEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this editor configuration entry.
	 *
	 * @return the primary key of this editor configuration entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this editor configuration entry.
	 *
	 * @param primaryKey the primary key of this editor configuration entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this editor configuration entry.
	 *
	 * @return the uuid of this editor configuration entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this editor configuration entry.
	 *
	 * @param uuid the uuid of this editor configuration entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the editor configuration entry ID of this editor configuration entry.
	 *
	 * @return the editor configuration entry ID of this editor configuration entry
	 */
	public long getEditorConfigurationEntryId();

	/**
	 * Sets the editor configuration entry ID of this editor configuration entry.
	 *
	 * @param editorConfigurationEntryId the editor configuration entry ID of this editor configuration entry
	 */
	public void setEditorConfigurationEntryId(long editorConfigurationEntryId);

	/**
	 * Returns the company ID of this editor configuration entry.
	 *
	 * @return the company ID of this editor configuration entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this editor configuration entry.
	 *
	 * @param companyId the company ID of this editor configuration entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this editor configuration entry.
	 *
	 * @return the create date of this editor configuration entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this editor configuration entry.
	 *
	 * @param createDate the create date of this editor configuration entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this editor configuration entry.
	 *
	 * @return the modified date of this editor configuration entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this editor configuration entry.
	 *
	 * @param modifiedDate the modified date of this editor configuration entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the portlet name of this editor configuration entry.
	 *
	 * @return the portlet name of this editor configuration entry
	 */
	@AutoEscape
	public String getPortletName();

	/**
	 * Sets the portlet name of this editor configuration entry.
	 *
	 * @param portletName the portlet name of this editor configuration entry
	 */
	public void setPortletName(String portletName);

	/**
	 * Returns the editor name of this editor configuration entry.
	 *
	 * @return the editor name of this editor configuration entry
	 */
	@AutoEscape
	public String getEditorName();

	/**
	 * Sets the editor name of this editor configuration entry.
	 *
	 * @param editorName the editor name of this editor configuration entry
	 */
	public void setEditorName(String editorName);

	/**
	 * Returns the editor config key of this editor configuration entry.
	 *
	 * @return the editor config key of this editor configuration entry
	 */
	@AutoEscape
	public String getEditorConfigKey();

	/**
	 * Sets the editor config key of this editor configuration entry.
	 *
	 * @param editorConfigKey the editor config key of this editor configuration entry
	 */
	public void setEditorConfigKey(String editorConfigKey);

	/**
	 * Returns the configuration of this editor configuration entry.
	 *
	 * @return the configuration of this editor configuration entry
	 */
	@AutoEscape
	public String getConfiguration();

	/**
	 * Sets the configuration of this editor configuration entry.
	 *
	 * @param configuration the configuration of this editor configuration entry
	 */
	public void setConfiguration(String configuration);

	/**
	 * Returns the enabled of this editor configuration entry.
	 *
	 * @return the enabled of this editor configuration entry
	 */
	public boolean getEnabled();

	/**
	 * Returns <code>true</code> if this editor configuration entry is enabled.
	 *
	 * @return <code>true</code> if this editor configuration entry is enabled; <code>false</code> otherwise
	 */
	public boolean isEnabled();

	/**
	 * Sets whether this editor configuration entry is enabled.
	 *
	 * @param enabled the enabled of this editor configuration entry
	 */
	public void setEnabled(boolean enabled);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(EditorConfigurationEntry editorConfigurationEntry);

	@Override
	public int hashCode();

	@Override
	public CacheModel<EditorConfigurationEntry> toCacheModel();

	@Override
	public EditorConfigurationEntry toEscapedModel();

	@Override
	public EditorConfigurationEntry toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}