dependencies {
	compileOnly group: "com.liferay.portal", name: "com.liferay.portal.kernel", version: "3.0.0"
	compileOnly group: "org.osgi", name: "osgi.cmpn", version: "6.0.0"
	compileOnly group: 'com.liferay', name: 'com.liferay.journal.api', version: '3.0.0'

	compileOnly group: 'org.osgi', name: 'org.osgi.framework', version: '1.9.0'

	compileOnly project(":modules:elastic-auto-tagger:auto-tagging-api")

	compileInclude group: 'com.fasterxml.jackson.core', name: 'jackson-core', version: '2.9.7'
	compileInclude group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.7'
	compileInclude group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.9.7'
}