/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.editor.configuration.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry;
import com.liferay.frontend.editor.configuration.model.EditorConfigurationEntryModel;

import com.liferay.petra.string.StringBundler;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the EditorConfigurationEntry service. Represents a row in the &quot;EditorConfigurationEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link EditorConfigurationEntryModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EditorConfigurationEntryImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EditorConfigurationEntryImpl
 * @see EditorConfigurationEntry
 * @see EditorConfigurationEntryModel
 * @generated
 */
@ProviderType
public class EditorConfigurationEntryModelImpl extends BaseModelImpl<EditorConfigurationEntry>
	implements EditorConfigurationEntryModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a editor configuration entry model instance should use the {@link EditorConfigurationEntry} interface instead.
	 */
	public static final String TABLE_NAME = "EditorConfigurationEntry";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "editorConfigurationEntryId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "portletName", Types.VARCHAR },
			{ "editorName", Types.VARCHAR },
			{ "editorConfigKey", Types.VARCHAR },
			{ "configuration", Types.VARCHAR },
			{ "enabled", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("editorConfigurationEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("portletName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("editorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("editorConfigKey", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("configuration", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("enabled", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table EditorConfigurationEntry (uuid_ VARCHAR(75) null,editorConfigurationEntryId LONG not null primary key,companyId LONG,createDate DATE null,modifiedDate DATE null,portletName VARCHAR(75) null,editorName VARCHAR(75) null,editorConfigKey VARCHAR(75) null,configuration VARCHAR(75) null,enabled BOOLEAN)";
	public static final String TABLE_SQL_DROP = "drop table EditorConfigurationEntry";
	public static final String ORDER_BY_JPQL = " ORDER BY editorConfigurationEntry.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY EditorConfigurationEntry.createDate DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.frontend.editor.configuration.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.frontend.editor.configuration.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.frontend.editor.configuration.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long EDITORCONFIGKEY_COLUMN_BITMASK = 2L;
	public static final long EDITORNAME_COLUMN_BITMASK = 4L;
	public static final long PORTLETNAME_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.frontend.editor.configuration.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry"));

	public EditorConfigurationEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _editorConfigurationEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEditorConfigurationEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _editorConfigurationEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EditorConfigurationEntry.class;
	}

	@Override
	public String getModelClassName() {
		return EditorConfigurationEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("editorConfigurationEntryId",
			getEditorConfigurationEntryId());
		attributes.put("companyId", getCompanyId());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("portletName", getPortletName());
		attributes.put("editorName", getEditorName());
		attributes.put("editorConfigKey", getEditorConfigKey());
		attributes.put("configuration", getConfiguration());
		attributes.put("enabled", isEnabled());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long editorConfigurationEntryId = (Long)attributes.get(
				"editorConfigurationEntryId");

		if (editorConfigurationEntryId != null) {
			setEditorConfigurationEntryId(editorConfigurationEntryId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String portletName = (String)attributes.get("portletName");

		if (portletName != null) {
			setPortletName(portletName);
		}

		String editorName = (String)attributes.get("editorName");

		if (editorName != null) {
			setEditorName(editorName);
		}

		String editorConfigKey = (String)attributes.get("editorConfigKey");

		if (editorConfigKey != null) {
			setEditorConfigKey(editorConfigKey);
		}

		String configuration = (String)attributes.get("configuration");

		if (configuration != null) {
			setConfiguration(configuration);
		}

		Boolean enabled = (Boolean)attributes.get("enabled");

		if (enabled != null) {
			setEnabled(enabled);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getEditorConfigurationEntryId() {
		return _editorConfigurationEntryId;
	}

	@Override
	public void setEditorConfigurationEntryId(long editorConfigurationEntryId) {
		_editorConfigurationEntryId = editorConfigurationEntryId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getPortletName() {
		if (_portletName == null) {
			return "";
		}
		else {
			return _portletName;
		}
	}

	@Override
	public void setPortletName(String portletName) {
		_columnBitmask |= PORTLETNAME_COLUMN_BITMASK;

		if (_originalPortletName == null) {
			_originalPortletName = _portletName;
		}

		_portletName = portletName;
	}

	public String getOriginalPortletName() {
		return GetterUtil.getString(_originalPortletName);
	}

	@Override
	public String getEditorName() {
		if (_editorName == null) {
			return "";
		}
		else {
			return _editorName;
		}
	}

	@Override
	public void setEditorName(String editorName) {
		_columnBitmask |= EDITORNAME_COLUMN_BITMASK;

		if (_originalEditorName == null) {
			_originalEditorName = _editorName;
		}

		_editorName = editorName;
	}

	public String getOriginalEditorName() {
		return GetterUtil.getString(_originalEditorName);
	}

	@Override
	public String getEditorConfigKey() {
		if (_editorConfigKey == null) {
			return "";
		}
		else {
			return _editorConfigKey;
		}
	}

	@Override
	public void setEditorConfigKey(String editorConfigKey) {
		_columnBitmask |= EDITORCONFIGKEY_COLUMN_BITMASK;

		if (_originalEditorConfigKey == null) {
			_originalEditorConfigKey = _editorConfigKey;
		}

		_editorConfigKey = editorConfigKey;
	}

	public String getOriginalEditorConfigKey() {
		return GetterUtil.getString(_originalEditorConfigKey);
	}

	@Override
	public String getConfiguration() {
		if (_configuration == null) {
			return "";
		}
		else {
			return _configuration;
		}
	}

	@Override
	public void setConfiguration(String configuration) {
		_configuration = configuration;
	}

	@Override
	public boolean getEnabled() {
		return _enabled;
	}

	@Override
	public boolean isEnabled() {
		return _enabled;
	}

	@Override
	public void setEnabled(boolean enabled) {
		_enabled = enabled;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				EditorConfigurationEntry.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			EditorConfigurationEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EditorConfigurationEntry toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (EditorConfigurationEntry)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EditorConfigurationEntryImpl editorConfigurationEntryImpl = new EditorConfigurationEntryImpl();

		editorConfigurationEntryImpl.setUuid(getUuid());
		editorConfigurationEntryImpl.setEditorConfigurationEntryId(getEditorConfigurationEntryId());
		editorConfigurationEntryImpl.setCompanyId(getCompanyId());
		editorConfigurationEntryImpl.setCreateDate(getCreateDate());
		editorConfigurationEntryImpl.setModifiedDate(getModifiedDate());
		editorConfigurationEntryImpl.setPortletName(getPortletName());
		editorConfigurationEntryImpl.setEditorName(getEditorName());
		editorConfigurationEntryImpl.setEditorConfigKey(getEditorConfigKey());
		editorConfigurationEntryImpl.setConfiguration(getConfiguration());
		editorConfigurationEntryImpl.setEnabled(isEnabled());

		editorConfigurationEntryImpl.resetOriginalValues();

		return editorConfigurationEntryImpl;
	}

	@Override
	public int compareTo(EditorConfigurationEntry editorConfigurationEntry) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				editorConfigurationEntry.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof EditorConfigurationEntry)) {
			return false;
		}

		EditorConfigurationEntry editorConfigurationEntry = (EditorConfigurationEntry)obj;

		long primaryKey = editorConfigurationEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		EditorConfigurationEntryModelImpl editorConfigurationEntryModelImpl = this;

		editorConfigurationEntryModelImpl._originalUuid = editorConfigurationEntryModelImpl._uuid;

		editorConfigurationEntryModelImpl._originalCompanyId = editorConfigurationEntryModelImpl._companyId;

		editorConfigurationEntryModelImpl._setOriginalCompanyId = false;

		editorConfigurationEntryModelImpl._setModifiedDate = false;

		editorConfigurationEntryModelImpl._originalPortletName = editorConfigurationEntryModelImpl._portletName;

		editorConfigurationEntryModelImpl._originalEditorName = editorConfigurationEntryModelImpl._editorName;

		editorConfigurationEntryModelImpl._originalEditorConfigKey = editorConfigurationEntryModelImpl._editorConfigKey;

		editorConfigurationEntryModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<EditorConfigurationEntry> toCacheModel() {
		EditorConfigurationEntryCacheModel editorConfigurationEntryCacheModel = new EditorConfigurationEntryCacheModel();

		editorConfigurationEntryCacheModel.uuid = getUuid();

		String uuid = editorConfigurationEntryCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			editorConfigurationEntryCacheModel.uuid = null;
		}

		editorConfigurationEntryCacheModel.editorConfigurationEntryId = getEditorConfigurationEntryId();

		editorConfigurationEntryCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			editorConfigurationEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			editorConfigurationEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			editorConfigurationEntryCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			editorConfigurationEntryCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		editorConfigurationEntryCacheModel.portletName = getPortletName();

		String portletName = editorConfigurationEntryCacheModel.portletName;

		if ((portletName != null) && (portletName.length() == 0)) {
			editorConfigurationEntryCacheModel.portletName = null;
		}

		editorConfigurationEntryCacheModel.editorName = getEditorName();

		String editorName = editorConfigurationEntryCacheModel.editorName;

		if ((editorName != null) && (editorName.length() == 0)) {
			editorConfigurationEntryCacheModel.editorName = null;
		}

		editorConfigurationEntryCacheModel.editorConfigKey = getEditorConfigKey();

		String editorConfigKey = editorConfigurationEntryCacheModel.editorConfigKey;

		if ((editorConfigKey != null) && (editorConfigKey.length() == 0)) {
			editorConfigurationEntryCacheModel.editorConfigKey = null;
		}

		editorConfigurationEntryCacheModel.configuration = getConfiguration();

		String configuration = editorConfigurationEntryCacheModel.configuration;

		if ((configuration != null) && (configuration.length() == 0)) {
			editorConfigurationEntryCacheModel.configuration = null;
		}

		editorConfigurationEntryCacheModel.enabled = isEnabled();

		return editorConfigurationEntryCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(21);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", editorConfigurationEntryId=");
		sb.append(getEditorConfigurationEntryId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", portletName=");
		sb.append(getPortletName());
		sb.append(", editorName=");
		sb.append(getEditorName());
		sb.append(", editorConfigKey=");
		sb.append(getEditorConfigKey());
		sb.append(", configuration=");
		sb.append(getConfiguration());
		sb.append(", enabled=");
		sb.append(isEnabled());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(34);

		sb.append("<model><model-name>");
		sb.append(
			"com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>editorConfigurationEntryId</column-name><column-value><![CDATA[");
		sb.append(getEditorConfigurationEntryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>portletName</column-name><column-value><![CDATA[");
		sb.append(getPortletName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>editorName</column-name><column-value><![CDATA[");
		sb.append(getEditorName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>editorConfigKey</column-name><column-value><![CDATA[");
		sb.append(getEditorConfigKey());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>configuration</column-name><column-value><![CDATA[");
		sb.append(getConfiguration());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>enabled</column-name><column-value><![CDATA[");
		sb.append(isEnabled());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = EditorConfigurationEntry.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			EditorConfigurationEntry.class, ModelWrapper.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _editorConfigurationEntryId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _portletName;
	private String _originalPortletName;
	private String _editorName;
	private String _originalEditorName;
	private String _editorConfigKey;
	private String _originalEditorConfigKey;
	private String _configuration;
	private boolean _enabled;
	private long _columnBitmask;
	private EditorConfigurationEntry _escapedModel;
}