include-and-override=${liferay.home}/portal-custom.properties
liferay.home=/workspaces/bundles
jdbc.default.driverClassName=com.mysql.cj.jdbc.Driver
jdbc.default.url=jdbc:mysql://localhost/lportal?characterEncoding=UTF-8&dontTrackOpenResources=true&holdResultsOpenOverStatementClose=true&serverTimezone=GMT&useFastDateParsing=false&useUnicode=true
jdbc.default.username=liferay
jdbc.default.password=liferay
enterprise.product.notification.enabled=false
company.default.web.id=liferay.com
company.default.locale=en_US
company.default.time.zone=UTC
company.security.strangers.verify=false
users.reminder.queries.enabled=false
users.reminder.queries.required=false
terms.of.use.required=false
passwords.encryption.algorithm=NONE
passwords.default.policy.change.required=false
default.admin.email.address.prefix=test
setup.wizard.enabled=false
feature.flag.ui.visible[dev]=true
module.framework.properties.osgi.console=11311
virtual.hosts.valid.hosts=localhost,127.0.0.1,[0:0:0:0:0:0:0:1]
admin.email.from.name=Test Test
admin.email.from.address=test@liferay.com

captcha.enforce.disabled=true