/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.frontend.editor.configuration.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry;
import com.liferay.frontend.editor.configuration.service.EditorConfigurationEntryLocalService;
import com.liferay.frontend.editor.configuration.service.persistence.EditorConfigurationEntryPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the editor configuration entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.frontend.editor.configuration.service.impl.EditorConfigurationEntryLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.frontend.editor.configuration.service.impl.EditorConfigurationEntryLocalServiceImpl
 * @see com.liferay.frontend.editor.configuration.service.EditorConfigurationEntryLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class EditorConfigurationEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements EditorConfigurationEntryLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.liferay.frontend.editor.configuration.service.EditorConfigurationEntryLocalServiceUtil} to access the editor configuration entry local service.
	 */

	/**
	 * Adds the editor configuration entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param editorConfigurationEntry the editor configuration entry
	 * @return the editor configuration entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EditorConfigurationEntry addEditorConfigurationEntry(
		EditorConfigurationEntry editorConfigurationEntry) {
		editorConfigurationEntry.setNew(true);

		return editorConfigurationEntryPersistence.update(editorConfigurationEntry);
	}

	/**
	 * Creates a new editor configuration entry with the primary key. Does not add the editor configuration entry to the database.
	 *
	 * @param editorConfigurationEntryId the primary key for the new editor configuration entry
	 * @return the new editor configuration entry
	 */
	@Override
	@Transactional(enabled = false)
	public EditorConfigurationEntry createEditorConfigurationEntry(
		long editorConfigurationEntryId) {
		return editorConfigurationEntryPersistence.create(editorConfigurationEntryId);
	}

	/**
	 * Deletes the editor configuration entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param editorConfigurationEntryId the primary key of the editor configuration entry
	 * @return the editor configuration entry that was removed
	 * @throws PortalException if a editor configuration entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EditorConfigurationEntry deleteEditorConfigurationEntry(
		long editorConfigurationEntryId) throws PortalException {
		return editorConfigurationEntryPersistence.remove(editorConfigurationEntryId);
	}

	/**
	 * Deletes the editor configuration entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param editorConfigurationEntry the editor configuration entry
	 * @return the editor configuration entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public EditorConfigurationEntry deleteEditorConfigurationEntry(
		EditorConfigurationEntry editorConfigurationEntry) {
		return editorConfigurationEntryPersistence.remove(editorConfigurationEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(EditorConfigurationEntry.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return editorConfigurationEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return editorConfigurationEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return editorConfigurationEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return editorConfigurationEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return editorConfigurationEntryPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public EditorConfigurationEntry fetchEditorConfigurationEntry(
		long editorConfigurationEntryId) {
		return editorConfigurationEntryPersistence.fetchByPrimaryKey(editorConfigurationEntryId);
	}

	/**
	 * Returns the editor configuration entry with the matching UUID and company.
	 *
	 * @param uuid the editor configuration entry's UUID
	 * @param companyId the primary key of the company
	 * @return the matching editor configuration entry, or <code>null</code> if a matching editor configuration entry could not be found
	 */
	@Override
	public EditorConfigurationEntry fetchEditorConfigurationEntryByUuidAndCompanyId(
		String uuid, long companyId) {
		return editorConfigurationEntryPersistence.fetchByUuid_C_First(uuid,
			companyId, null);
	}

	/**
	 * Returns the editor configuration entry with the primary key.
	 *
	 * @param editorConfigurationEntryId the primary key of the editor configuration entry
	 * @return the editor configuration entry
	 * @throws PortalException if a editor configuration entry with the primary key could not be found
	 */
	@Override
	public EditorConfigurationEntry getEditorConfigurationEntry(
		long editorConfigurationEntryId) throws PortalException {
		return editorConfigurationEntryPersistence.findByPrimaryKey(editorConfigurationEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(editorConfigurationEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EditorConfigurationEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"editorConfigurationEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(editorConfigurationEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(EditorConfigurationEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"editorConfigurationEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(editorConfigurationEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(EditorConfigurationEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"editorConfigurationEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<EditorConfigurationEntry>() {
				@Override
				public void performAction(
					EditorConfigurationEntry editorConfigurationEntry)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						editorConfigurationEntry);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(
					EditorConfigurationEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return editorConfigurationEntryLocalService.deleteEditorConfigurationEntry((EditorConfigurationEntry)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return editorConfigurationEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the editor configuration entry with the matching UUID and company.
	 *
	 * @param uuid the editor configuration entry's UUID
	 * @param companyId the primary key of the company
	 * @return the matching editor configuration entry
	 * @throws PortalException if a matching editor configuration entry could not be found
	 */
	@Override
	public EditorConfigurationEntry getEditorConfigurationEntryByUuidAndCompanyId(
		String uuid, long companyId) throws PortalException {
		return editorConfigurationEntryPersistence.findByUuid_C_First(uuid,
			companyId, null);
	}

	/**
	 * Returns a range of all the editor configuration entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.liferay.frontend.editor.configuration.model.impl.EditorConfigurationEntryModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of editor configuration entries
	 * @param end the upper bound of the range of editor configuration entries (not inclusive)
	 * @return the range of editor configuration entries
	 */
	@Override
	public List<EditorConfigurationEntry> getEditorConfigurationEntries(
		int start, int end) {
		return editorConfigurationEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of editor configuration entries.
	 *
	 * @return the number of editor configuration entries
	 */
	@Override
	public int getEditorConfigurationEntriesCount() {
		return editorConfigurationEntryPersistence.countAll();
	}

	/**
	 * Updates the editor configuration entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param editorConfigurationEntry the editor configuration entry
	 * @return the editor configuration entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public EditorConfigurationEntry updateEditorConfigurationEntry(
		EditorConfigurationEntry editorConfigurationEntry) {
		return editorConfigurationEntryPersistence.update(editorConfigurationEntry);
	}

	/**
	 * Returns the editor configuration entry local service.
	 *
	 * @return the editor configuration entry local service
	 */
	public EditorConfigurationEntryLocalService getEditorConfigurationEntryLocalService() {
		return editorConfigurationEntryLocalService;
	}

	/**
	 * Sets the editor configuration entry local service.
	 *
	 * @param editorConfigurationEntryLocalService the editor configuration entry local service
	 */
	public void setEditorConfigurationEntryLocalService(
		EditorConfigurationEntryLocalService editorConfigurationEntryLocalService) {
		this.editorConfigurationEntryLocalService = editorConfigurationEntryLocalService;
	}

	/**
	 * Returns the editor configuration entry persistence.
	 *
	 * @return the editor configuration entry persistence
	 */
	public EditorConfigurationEntryPersistence getEditorConfigurationEntryPersistence() {
		return editorConfigurationEntryPersistence;
	}

	/**
	 * Sets the editor configuration entry persistence.
	 *
	 * @param editorConfigurationEntryPersistence the editor configuration entry persistence
	 */
	public void setEditorConfigurationEntryPersistence(
		EditorConfigurationEntryPersistence editorConfigurationEntryPersistence) {
		this.editorConfigurationEntryPersistence = editorConfigurationEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry",
			editorConfigurationEntryLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.liferay.frontend.editor.configuration.model.EditorConfigurationEntry");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EditorConfigurationEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return EditorConfigurationEntry.class;
	}

	protected String getModelClassName() {
		return EditorConfigurationEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = editorConfigurationEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = EditorConfigurationEntryLocalService.class)
	protected EditorConfigurationEntryLocalService editorConfigurationEntryLocalService;
	@BeanReference(type = EditorConfigurationEntryPersistence.class)
	protected EditorConfigurationEntryPersistence editorConfigurationEntryPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}