#
# This is a generated file.
#

api.version=v1.0
batch.engine.entity.class.name=com.liferay.object.rest.dto.v1_0.Folder2
batch.engine.task.item.delegate=true
batch.planner.export.enabled=false
batch.planner.import.enabled=false
entity.class.name=com.liferay.object.rest.dto.v1_0.Folder2
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.Object)
osgi.jaxrs.resource=true