#
# This is a generated file.
#

api.version=v1.0
feature.flag.key=LPD-62272
openapi.resource=true
openapi.resource.path=/ai-hub-cell
osgi.jaxrs.application.select=(osgi.jaxrs.name=Liferay.AI.Hub.Cell.REST)
osgi.jaxrs.resource=true