on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Sync upstream changes     
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      with:
        target_sync_branch: master
        target_repo_token: ${{ github.token }}
        upstream_sync_branch: master
        upstream_sync_repo: liferay/liferay-portal
