name: Sync Upstream
on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if organization member
      id: check-org
      uses: jamessingleton/is-organization-member@1.0.1
      with:
        organization: liferay
        token: ${{ github.token }}
    - uses: aormsby/Fork-Sync-With-Upstream-action@v3.2
      if: ${{ steps.check-org.outputs.result }}
      with:
        target_sync_branch: master
        target_repo_token: ${{ github.token }}
        upstream_sync_branch: master
        upstream_sync_repo: liferay/liferay-portal
